version: '3'

services:
  node:
    image: fnagel/docker-jqueryui:${DOCKER_NODE_TAG}
    container_name: '${COMPOSE_PROJECT_NAME}-node'
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        node_tag: ${DOCKER_NODE_TAG}
    user: "node"
    environment:
      - NODE_ENV=production
    volumes:
      - app:/home/node/app
    expose:
      - "8088/tcp"
    ports:
      - "80:8088"

volumes:
  app:
